Vagrant.configure('2') do |config|
  config.ssh.username = "ubuntu"
  config.ssh.private_key_path = "~/.ssh/key.pem"

  config.vm.provider "openstack" do |os|
    os.openstack_auth_url = "http://8.43.86.2:5000/v2.0/tokens"
    os.username = "facebook10208069315396714"
    os.password = "6hG6ztLEWzRgWOsH"
    os.tenant_name = "facebook10208069315396714"	

    # Specify instance information
    os.server_name = "ubuntu"
    os.flavor = "m1.smaller"
    os.image = "Ubuntu14.04"
    os.floating_ip_pool = "public"
    os.networks = "ubuntu-redes"
    os.keypair_name = "key"
    os.security_groups = ["default"]
  end

  config.vm.provision "ansible" do |op|
    op.verbose = "v"	
    op.playbook = "script.yml"
  end 	
end
